// Generated by gencpp from file ti_mmwave_rospkg/RadarOccupancy.msg
// DO NOT EDIT!


#ifndef TI_MMWAVE_ROSPKG_MESSAGE_RADAROCCUPANCY_H
#define TI_MMWAVE_ROSPKG_MESSAGE_RADAROCCUPANCY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace ti_mmwave_rospkg
{
template <class ContainerAllocator>
struct RadarOccupancy_
{
  typedef RadarOccupancy_<ContainerAllocator> Type;

  RadarOccupancy_()
    : header()
    , state(0)  {
    }
  RadarOccupancy_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , state(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _state_type;
  _state_type state;





  typedef boost::shared_ptr< ::ti_mmwave_rospkg::RadarOccupancy_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ti_mmwave_rospkg::RadarOccupancy_<ContainerAllocator> const> ConstPtr;

}; // struct RadarOccupancy_

typedef ::ti_mmwave_rospkg::RadarOccupancy_<std::allocator<void> > RadarOccupancy;

typedef boost::shared_ptr< ::ti_mmwave_rospkg::RadarOccupancy > RadarOccupancyPtr;
typedef boost::shared_ptr< ::ti_mmwave_rospkg::RadarOccupancy const> RadarOccupancyConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ti_mmwave_rospkg::RadarOccupancy_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ti_mmwave_rospkg::RadarOccupancy_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ti_mmwave_rospkg::RadarOccupancy_<ContainerAllocator1> & lhs, const ::ti_mmwave_rospkg::RadarOccupancy_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.state == rhs.state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ti_mmwave_rospkg::RadarOccupancy_<ContainerAllocator1> & lhs, const ::ti_mmwave_rospkg::RadarOccupancy_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ti_mmwave_rospkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ti_mmwave_rospkg::RadarOccupancy_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ti_mmwave_rospkg::RadarOccupancy_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ti_mmwave_rospkg::RadarOccupancy_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ti_mmwave_rospkg::RadarOccupancy_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ti_mmwave_rospkg::RadarOccupancy_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ti_mmwave_rospkg::RadarOccupancy_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ti_mmwave_rospkg::RadarOccupancy_<ContainerAllocator> >
{
  static const char* value()
  {
    return "461b1067e1ee73ecfebc21c633ae913d";
  }

  static const char* value(const ::ti_mmwave_rospkg::RadarOccupancy_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x461b1067e1ee73ecULL;
  static const uint64_t static_value2 = 0xfebc21c633ae913dULL;
};

template<class ContainerAllocator>
struct DataType< ::ti_mmwave_rospkg::RadarOccupancy_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ti_mmwave_rospkg/RadarOccupancy";
  }

  static const char* value(const ::ti_mmwave_rospkg::RadarOccupancy_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ti_mmwave_rospkg::RadarOccupancy_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"uint32 state\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::ti_mmwave_rospkg::RadarOccupancy_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ti_mmwave_rospkg::RadarOccupancy_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RadarOccupancy_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ti_mmwave_rospkg::RadarOccupancy_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ti_mmwave_rospkg::RadarOccupancy_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "state: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TI_MMWAVE_ROSPKG_MESSAGE_RADAROCCUPANCY_H
