// Generated by gencpp from file ti_mmwave_tracker_rospkg/RadarPointTrackID.msg
// DO NOT EDIT!


#ifndef TI_MMWAVE_TRACKER_ROSPKG_MESSAGE_RADARPOINTTRACKID_H
#define TI_MMWAVE_TRACKER_ROSPKG_MESSAGE_RADARPOINTTRACKID_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace ti_mmwave_tracker_rospkg
{
template <class ContainerAllocator>
struct RadarPointTrackID_
{
  typedef RadarPointTrackID_<ContainerAllocator> Type;

  RadarPointTrackID_()
    : header()
    , tid(0)  {
    }
  RadarPointTrackID_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , tid(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _tid_type;
  _tid_type tid;





  typedef boost::shared_ptr< ::ti_mmwave_tracker_rospkg::RadarPointTrackID_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ti_mmwave_tracker_rospkg::RadarPointTrackID_<ContainerAllocator> const> ConstPtr;

}; // struct RadarPointTrackID_

typedef ::ti_mmwave_tracker_rospkg::RadarPointTrackID_<std::allocator<void> > RadarPointTrackID;

typedef boost::shared_ptr< ::ti_mmwave_tracker_rospkg::RadarPointTrackID > RadarPointTrackIDPtr;
typedef boost::shared_ptr< ::ti_mmwave_tracker_rospkg::RadarPointTrackID const> RadarPointTrackIDConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ti_mmwave_tracker_rospkg::RadarPointTrackID_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ti_mmwave_tracker_rospkg::RadarPointTrackID_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ti_mmwave_tracker_rospkg::RadarPointTrackID_<ContainerAllocator1> & lhs, const ::ti_mmwave_tracker_rospkg::RadarPointTrackID_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.tid == rhs.tid;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ti_mmwave_tracker_rospkg::RadarPointTrackID_<ContainerAllocator1> & lhs, const ::ti_mmwave_tracker_rospkg::RadarPointTrackID_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ti_mmwave_tracker_rospkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ti_mmwave_tracker_rospkg::RadarPointTrackID_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ti_mmwave_tracker_rospkg::RadarPointTrackID_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ti_mmwave_tracker_rospkg::RadarPointTrackID_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ti_mmwave_tracker_rospkg::RadarPointTrackID_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ti_mmwave_tracker_rospkg::RadarPointTrackID_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ti_mmwave_tracker_rospkg::RadarPointTrackID_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ti_mmwave_tracker_rospkg::RadarPointTrackID_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c7518afac70459a691ba924d05457d35";
  }

  static const char* value(const ::ti_mmwave_tracker_rospkg::RadarPointTrackID_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc7518afac70459a6ULL;
  static const uint64_t static_value2 = 0x91ba924d05457d35ULL;
};

template<class ContainerAllocator>
struct DataType< ::ti_mmwave_tracker_rospkg::RadarPointTrackID_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ti_mmwave_tracker_rospkg/RadarPointTrackID";
  }

  static const char* value(const ::ti_mmwave_tracker_rospkg::RadarPointTrackID_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ti_mmwave_tracker_rospkg::RadarPointTrackID_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"uint8 tid\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::ti_mmwave_tracker_rospkg::RadarPointTrackID_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ti_mmwave_tracker_rospkg::RadarPointTrackID_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.tid);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RadarPointTrackID_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ti_mmwave_tracker_rospkg::RadarPointTrackID_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ti_mmwave_tracker_rospkg::RadarPointTrackID_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "tid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.tid);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TI_MMWAVE_TRACKER_ROSPKG_MESSAGE_RADARPOINTTRACKID_H
