// Generated by gencpp from file ti_mmwave_tracker_rospkg/RadarTrackArray.msg
// DO NOT EDIT!


#ifndef TI_MMWAVE_TRACKER_ROSPKG_MESSAGE_RADARTRACKARRAY_H
#define TI_MMWAVE_TRACKER_ROSPKG_MESSAGE_RADARTRACKARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <ti_mmwave_tracker_rospkg/RadarTrackContents.h>

namespace ti_mmwave_tracker_rospkg
{
template <class ContainerAllocator>
struct RadarTrackArray_
{
  typedef RadarTrackArray_<ContainerAllocator> Type;

  RadarTrackArray_()
    : header()
    , num_tracks(0)
    , track()  {
    }
  RadarTrackArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , num_tracks(0)
    , track(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _num_tracks_type;
  _num_tracks_type num_tracks;

   typedef std::vector< ::ti_mmwave_tracker_rospkg::RadarTrackContents_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::ti_mmwave_tracker_rospkg::RadarTrackContents_<ContainerAllocator> >> _track_type;
  _track_type track;





  typedef boost::shared_ptr< ::ti_mmwave_tracker_rospkg::RadarTrackArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ti_mmwave_tracker_rospkg::RadarTrackArray_<ContainerAllocator> const> ConstPtr;

}; // struct RadarTrackArray_

typedef ::ti_mmwave_tracker_rospkg::RadarTrackArray_<std::allocator<void> > RadarTrackArray;

typedef boost::shared_ptr< ::ti_mmwave_tracker_rospkg::RadarTrackArray > RadarTrackArrayPtr;
typedef boost::shared_ptr< ::ti_mmwave_tracker_rospkg::RadarTrackArray const> RadarTrackArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ti_mmwave_tracker_rospkg::RadarTrackArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ti_mmwave_tracker_rospkg::RadarTrackArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ti_mmwave_tracker_rospkg::RadarTrackArray_<ContainerAllocator1> & lhs, const ::ti_mmwave_tracker_rospkg::RadarTrackArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.num_tracks == rhs.num_tracks &&
    lhs.track == rhs.track;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ti_mmwave_tracker_rospkg::RadarTrackArray_<ContainerAllocator1> & lhs, const ::ti_mmwave_tracker_rospkg::RadarTrackArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ti_mmwave_tracker_rospkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ti_mmwave_tracker_rospkg::RadarTrackArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ti_mmwave_tracker_rospkg::RadarTrackArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ti_mmwave_tracker_rospkg::RadarTrackArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ti_mmwave_tracker_rospkg::RadarTrackArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ti_mmwave_tracker_rospkg::RadarTrackArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ti_mmwave_tracker_rospkg::RadarTrackArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ti_mmwave_tracker_rospkg::RadarTrackArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4c57d9f86b51b7fa5872677d0abca61c";
  }

  static const char* value(const ::ti_mmwave_tracker_rospkg::RadarTrackArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4c57d9f86b51b7faULL;
  static const uint64_t static_value2 = 0x5872677d0abca61cULL;
};

template<class ContainerAllocator>
struct DataType< ::ti_mmwave_tracker_rospkg::RadarTrackArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ti_mmwave_tracker_rospkg/RadarTrackArray";
  }

  static const char* value(const ::ti_mmwave_tracker_rospkg::RadarTrackArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ti_mmwave_tracker_rospkg::RadarTrackArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"uint32 num_tracks\n"
"RadarTrackContents[] track\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: ti_mmwave_tracker_rospkg/RadarTrackContents\n"
"Header header\n"
"uint32 tid\n"
"float32 posx\n"
"float32 posy\n"
"float32 posz\n"
"float32 velx\n"
"float32 vely\n"
"float32 velz\n"
"float32 accx\n"
"float32 accy\n"
"float32 accz\n"
;
  }

  static const char* value(const ::ti_mmwave_tracker_rospkg::RadarTrackArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ti_mmwave_tracker_rospkg::RadarTrackArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.num_tracks);
      stream.next(m.track);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RadarTrackArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ti_mmwave_tracker_rospkg::RadarTrackArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ti_mmwave_tracker_rospkg::RadarTrackArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "num_tracks: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.num_tracks);
    s << indent << "track[]" << std::endl;
    for (size_t i = 0; i < v.track.size(); ++i)
    {
      s << indent << "  track[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::ti_mmwave_tracker_rospkg::RadarTrackContents_<ContainerAllocator> >::stream(s, indent + "    ", v.track[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TI_MMWAVE_TRACKER_ROSPKG_MESSAGE_RADARTRACKARRAY_H
